# This file sets up the networking necessary for Atlas
# 
# NOTE: Currently a dummy intermediate file
#
# Alec Thompson, 2015
# 

FROM base/whrl:latest
MAINTAINER Alec Thompson "ajthompson042@gmail.com"

