# Dummy container for the final container for consistent naming
#
# Alec Thompson, 2015
#

# Comment out/uncomment whichever import is necessary
FROM nvidia-drivers/whrl:latest
# FROM cuda/whrl:latest
MAINTAINER Alec Thompson "ajthompson042@gmail.com"

